string a1 = "Понедельник";
string a2 = "Вторник";
string a3 = "Среда";
string a4 = "Четверг";
string a5 = "Пятница";
string a6 = "Субота";
string a7 = "Воскресенье";
Double a8 =0;
string a9;
Console.Write("Vote day number:");
a9=Console.ReadLine();
a8=Convert.ToDouble(a9);
if (a8==1) System.Console.WriteLine(a1);
if (a8==2) System.Console.WriteLine(a2);
if (a8==3) System.Console.WriteLine(a3);
if (a8==4) System.Console.WriteLine(a4);
if (a8==5) System.Console.WriteLine(a5);
if (a8==6) System.Console.WriteLine(a6);
if (a8==7) System.Console.WriteLine(a7);